### ISSUE TITLE
Macro for asm-code inline 

### ISSUE THREAD

**Issue by redirectme** [Veltas/zenv#4]
I suggest a macro ASM_INLINE ... END_INLINE  to include asm-code into a DX-sequence:
```
	IF tokenised
		MACRO ASM_INLINE
	    		DB high($+2), low($+2)
		ENDM
	ELSE
		MACRO ASM_INLINE
	    		DW $+2	
		ENDM
	ENDIF

	MACRO END_INLINE
	    LD IY,$+7
	    JP next		
	ENDM
```
This macro can be placed into zenv.asm after MACRO HEADER, for example. 

There are  small Forth-words (few asm-instructions) but "JP next" is an expensive operation. Including code allows us to improve efficiency (by decreasing clarity, perhaps). 
For example, let's use this macro in "DABS" (zenv.asm).
```
	; ( d -- |d|)    - in original zenv.asm incomplete comment "; ( d -- d)"
	; : DABS
	HEADER dabs, "DABS", 0
dabs:
	CALL colon_code
	; DUP 0< IF
	DX dup
	DX zero_less
	DX if_raw
	DB .then-$-1
         	; 0. 2SWAP D-
	      ASM_INLINE		
         	LD DE,0
         	POP BC
         	PUSH DE
         	PUSH DE
         	PUSH BC
	      END_INLINE
              	;( 0 d ) 		
	      DX d_minus 
	; THEN ;
.then:
	DX exit
```

**Comment by redirectme** [comment]
There is a better macro END_INLINE:
```
	MACRO END_INLINE
		call end_inline	
	ENDM
```
The label end_line must be in colon_code:

```
; CALL colon_code in code
colon_code:
	; Push current PC to RS
	DEC IX
	DEC IX
	PUSH IY
	POP BC
	LD (IX+0), C
	LD (IX+1), B
	; Get new PC from stack
end_inline:
	POP IY
	; fall through
```

**Comment by Veltas** [comment]
This is a great idea, and the code all looks nicely optimised/clean. I will play around with this after work.

I will probably not add it because I don't like writing colon words that couldn't (mostly) be compiled at the interpreter. I can't think about how to add inlining to the current compiler, without significantly increasing the size of the binary. (Load time is important to me, since I do test the system on an actual Spectrum as well as an emulator, and want it to be as 'real' and practical as I can, this is why the Forth is tokenised by default).

I am currently working on a direct threaded x86-64 Forth for UEFI, and I will probably apply this idea there, where I don't mind the compiler being more sophisticated.

**Comment by redirectme** [comment]
A inline code is mostly faster but larger (especially when compared to tokenized system). Sometimes you can win both speed and size if you replace a few Forth-words (with literals) to a code. However the disadvantage of inline code is that decompiling back to the original source code becomes very difficult. You may want to add a decompiler in the future. 

The entry "end_inline:" can be useful even now (without inline macro).  Your system has several "POP IY \ JP next" fragments. This can be replaced with "JP end_inline" (it might be better to rename the label "end_inline" for clarity).

**Comment by Veltas** [comment]
> A inline code is mostly faster but larger (especially when compared to tokenized system). Sometimes you can win both speed and size if you replace a few Forth-words (with literals) to a code. However the disadvantage of inline code is that decompiling back to the original source code becomes very difficult. You may want to add a decompiler in the future.

Yes, these are some of the considerations I have had. Although I don't expect to add a decompiler.

> The entry "end_inline:" can be useful even now (without inline macro). Your system has several "POP IY \ JP next" fragments. This can be replaced with "JP end_inline" (it might be better to rename the label "end_inline" for clarity).

Good idea, I'll replace those.

**Comment by Veltas** [comment]
I've added the POP IY \ JP next shortcut in 4e720da5, closing this issue without fixing because I do not want to add inlining as if I spend more time on this project I will probably write a trivial cross-compiler to allow writing Forth source code instead of this assembly macro stuff, which would probably be too dumb for inline assembly.
